// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzRrtgcqCyzdoYEhbYyJlxIO5BBuaMBnw',
    appId: '1:502841222585:web:e6cc34f9c45fd635630268',
    messagingSenderId: '502841222585',
    projectId: 'chat-backend-6027d',
    authDomain: 'chat-backend-6027d.firebaseapp.com',
    storageBucket: 'chat-backend-6027d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOUwdQKdRJZba3mACU1a4-8VYruxBHdK0',
    appId: '1:502841222585:android:d43b35b2131e6c0c630268',
    messagingSenderId: '502841222585',
    projectId: 'chat-backend-6027d',
    storageBucket: 'chat-backend-6027d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp529e5_ys4nwR1iS4Q6718QFWUrV79fo',
    appId: '1:502841222585:ios:5695bc323833fb9a630268',
    messagingSenderId: '502841222585',
    projectId: 'chat-backend-6027d',
    storageBucket: 'chat-backend-6027d.appspot.com',
    androidClientId: '502841222585-pr9ar5494nm2h92shq33q7k3upeuo5di.apps.googleusercontent.com',
    iosClientId: '502841222585-0nmd6po4lhe728tajc10jsm0iti0ncra.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp529e5_ys4nwR1iS4Q6718QFWUrV79fo',
    appId: '1:502841222585:ios:55769881416795d8630268',
    messagingSenderId: '502841222585',
    projectId: 'chat-backend-6027d',
    storageBucket: 'chat-backend-6027d.appspot.com',
    androidClientId: '502841222585-pr9ar5494nm2h92shq33q7k3upeuo5di.apps.googleusercontent.com',
    iosClientId: '502841222585-ul3p96d0dlbjcah7ceton63op24hp2pe.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatModule.RunnerTests',
  );
}
